apiVersion: v1
kind: Service
metadata:
  name: store-service
  labels:
    run: store-service
spec:
  type: ClusterIP
  ports:
  - port: 7700
    protocol: TCP
    targetPort: 7700
  selector:
    app: store