apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    run: api-service
spec:
  type: LoadBalancer
  ports:
  - port: 7710
    protocol: TCP
    targetPort: 7710
  selector:
    app: api