apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  replicas: 3
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: caquicode/configserver:0.0.1-SNAPSHOT
        ports:
        - containerPort: 7715
        env:
        - name: PORT
          value: "7715"
        - name: CONFIG_REPOSITORY
          value: "https://github.com/jtviegas/spring-microservices"
