server:
  port: ${PORT:7705}
spring:
  application:
    name: solver-api
org.aprestos.labs.apis.springboot2.solver:
  blocking-coefficient: ${BLOCKING_COEFFICIENT:0.0}
org.aprestos.labs.apis.springboot2.uri.store:
  scheme: ${STORE_URI_SCHEME:http}
  host: ${STORE_URI_HOST:store}
  port: ${STORE_PORT:7700}
  path: ${STORE_URI_PATH:/store/task}
