server:
  port: ${PORT:7700}
spring:
  application:
    name: store-api
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.HSQLDialect
      hibernate.show_sql: false
    hibernate:
      ddl-auto: create-drop
org:
  aprestos:
    labs:
      spring:
        microservices:
          fsstore:
            rootLocation: /var/tmp/
